export enum PopupType {
  LOGIN = 'LOGIN',
  CHANGE_AVATAR = 'CHANGE_AVATAR',
  CREATE_LIST = 'CREATE_LIST',
  ADD_RECOMMENDATION = 'ADD_RECOMMENDATION',
  EDIT_RECOMMENDATION = 'EDIT_RECOMMENDATION',
  ADD_TO_LIST = 'ADD_TO_LIST',
  LIST_ANALYTICS = 'LIST_ANALYTICS',
  AD_NOTIFICATION = 'AD_NOTIFICATION',
}

export type PopupParams = any
